### ISSUE TITLE
为何在项目里使用openai调用gpt接口，会报错，java.net.SocketTimeoutException: connect timed out，是需要做什么设置吗？

### ISSUE THREAD

**Issue by Twinhead880** [Starcloud-Cloud/java-langchain#1]
openAiService.createChatCompletion(chatCompletionRequest);调用这句代码时会报错，java.net.SocketTimeoutException: connect timed out。我能科学上网，也有apikey，在其他项目里访问使用相同的apikey也能访问openai接口，但在本项目里就会报错，是需要什么特别的设置吗？很困扰，如果可以，请尽快给我一份回复？

**Comment by df007df** [comment]
> openAiService.createChatCompletion(chatCompletionRequest);调用这句代码时会报错，java.net.SocketTimeoutException: connect timed out。我能科学上网，也有apikey，在其他项目里访问使用相同的apikey也能访问openai接口，但在本项目里就会报错，是需要什么特别的设置吗？很困扰，如果可以，请尽快给我一份回复？

看下新的配置，可能你的代理配置不对了
