### ISSUE TITLE
prompt是否支持面向对象

### ISSUE THREAD

**Issue by kkkklzzzz** [Starcloud-Cloud/java-langchain#3]
例如我在模板中构建一个{question}对象，包含{level}，{number}这几个属性，我能否直接通过BaseVARIABLE.newObject赋值？

**Comment by df007df** [comment]
不行，这里的实现只是简单的字符串替换。变量都是”同级“的关系。

**Comment by kkkklzzzz** [comment]
> 不行，这里的实现只是简单的字符串替换。变量都是”同级“的关系。

好的感谢，还有一个问题，就是promptTemplate中未被传值的参数可以给定默认值吗？
例如：对错题/判断题：{numberOfTrueFalseQuestions}，每题{marksPerTrueFalseQuestion}分
  - 配对题：{numberOfMatchingQuestions}，每题{marksPerMatchingQuestion}分
  我的prompt文本未给这些参数赋值，能否让其默认为空或者指定一个值

**Comment by df007df** [comment]
> > 不行，这里的实现只是简单的字符串替换。变量都是”同级“的关系。
> 
> 好的感谢，还有一个问题，就是promptTemplate中未被传值的参数可以给定默认值吗？ 例如：对错题/判断题：{numberOfTrueFalseQuestions}，每题{marksPerTrueFalseQuestion}分
> 
> * 配对题：{numberOfMatchingQuestions}，每题{marksPerMatchingQuestion}分
>   我的prompt文本未给这些参数赋值，能否让其默认为空或者指定一个值

你应该把默认值判断放在上游自己的业务逻辑中。
