### ISSUE TITLE
与官方 langChain 的区别问题

### ISSUE THREAD

**Issue by liujunao** [Starcloud-Cloud/java-langchain#4]
java-langChain 是原封不动用 java 重新实现了一遍了吗？
如果是的话，会保持与官方 langChain 的更新进度吗；
如果不是的话，那与官方 langChain 有什么不同呢，比如：多了什么功能，少了什么功能？

**Comment by df007df** [comment]
> java-langChain 是原封不动用 java 重新实现了一遍了吗？ 如果是的话，会保持与官方 langChain 的更新进度吗； 如果不是的话，那与官方 langChain 有什么不同呢，比如：多了什么功能，少了什么功能？

这项目是在去年2月份开始的，主要当时没有java。是参考langChain python核心实现了一遍，完成了基本功能。现在自己还在用，不过生态上还是推荐python版本（python推出了更多强大的功能）。
此项目更多的是学习使用。

**Comment by liujunao** [comment]
后续还会保持一些功能的更新吗

**Comment by liujunao** [comment]
> > java-langChain 是原封不动用 java 重新实现了一遍了吗？ 如果是的话，会保持与官方 langChain 的更新进度吗； 如果不是的话，那与官方 langChain 有什么不同呢，比如：多了什么功能，少了什么功能？
> 
> 这项目是在去年2月份开始的，主要当时没有java。是参考langChain python核心实现了一遍，完成了基本功能。现在自己还在用，不过生态上还是推荐python版本（python推出了更多强大的功能）。 此项目更多的是学习使用。

再咨询个问题蛤，这个 java 实现，在 agent 里支持 agent 间的互调吗，就是也可以将 agent 抽象为 tool 来使用

**Comment by df007df** [comment]
> > > java-langChain 是原封不动用 java 重新实现了一遍了吗？ 如果是的话，会保持与官方 langChain 的更新进度吗； 如果不是的话，那与官方 langChain 有什么不同呢，比如：多了什么功能，少了什么功能？
> > 
> > 
> > 这项目是在去年2月份开始的，主要当时没有java。是参考langChain python核心实现了一遍，完成了基本功能。现在自己还在用，不过生态上还是推荐python版本（python推出了更多强大的功能）。 此项目更多的是学习使用。
> 
> 再咨询个问题蛤，这个 java 实现，在 agent 里支持 agent 间的互调吗，就是也可以将 agent 抽象为 tool 来使用

这里代码上没有实现（你可以优化下），逻辑上确实就是把 agent 定义为一个tool 而已。可以认为这些都是 function，相互调用而已。
